// commonConfig.js

const CommonConfig = {
    TAG_UUID: "Uuid",
    TAG_GR_UUID: "GrUuid",
    TAG_STREAM_CFG: "StreamCfg",
    TAG_TIME_CFG: "TimeCfg",
    TAG_EMAIL_CFG: "EmailCfg",
    TAG_VIDEO_CFG: "VideoCfg",
    TAG_DISPLAY_CFG: "DisplayCfg",
    TAG_OSD_CFG: "OsdCfg",
    TAG_RECORD_CFG: "RecordCfg",
    TAG_IMAGE_CFG: "ImageCfg",
    TAG_MD_CFG: "MdCfg",
    TAG_DEV_INFO: "DevInfo",
    TAG_NET_INFO: "NetworkInfo",
    TAG_PTZ_CFG: "PtzCfg",
    TAG_VIDEO_CH011: "VideoCh011",
    TAG_VIDEO_CH012: "VideoCh012",
    TAG_VIDEO_CH013: "VideoCh013",
    TAG_RECORD_CH011: "RecordCh011",
    TAG_RECORD_CH012: "RecordCh012",
    TAG_RECORD_SCH: "RecordSch",
    ADDR_ID_BROADCAST: -1,
    ADDR_ID_CONF_SERVER: 0,
    MSG_TYPE_KEEP_ALIVE: 0,
    MSG_TYPE_GET_CONFIG: 1,
    MSG_TYPE_SET_CONFIG: 2,
    MSG_TYPE_AUDIO: 3,
    MSG_TYPE_FILE: 4,
    MSG_TYPE_DISCONNECT: 5,
    MSG_TYPE_GET_STATUS: 6,
    MSG_TYPE_GET_CLI_STATS: 7,
    MSG_TYPE_GET_GRP_STATS: 8,
    MSG_TYPE_ALARM: 9,
    MSG_TYPE_FACTORY_DFLT: 10,
    MSG_TYPE_REBOOT: 11,
    MSG_TYPE_REDIRECT: 12,
    MSG_TYPE_EMail_publishURL_cameraName: 104,
    MSG_TYPE_GET_LIST: 54,
    MSG_TYPE_GET_VIDEO_FILE: 53,
    MSG_TYPE_CANCEL_VIDEO_FILE: 55,
  };
  
  module.exports = CommonConfig;
  